from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
from flask_jwt_extended import (
    JWTManager,
    create_access_token,
    jwt_required,
    get_jwt_identity
)

from config import Config
from utils import (
    analyze_health,
    calculate_green_score,
    estimate_environmental_impact,
    generate_medical_summary
)

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER

import logging
import io
import os

# --------------------------------
# App Initialization
# --------------------------------

app = Flask(__name__)
app.config.from_object(Config)

CORS(app, resources={r"/*": {"origins": app.config["ALLOWED_ORIGINS"]}})

jwt = JWTManager(app)

logging.basicConfig(level=logging.INFO)

# --------------------------------
# Dummy Users (Replace with DB Later)
# --------------------------------

users = {
    "admin": "1234",
    "kunj": "password"
}

# --------------------------------
# HOME ROUTE
# --------------------------------

@app.route("/")
def home():
    return "🚑 CareBridge AI Secure Backend Running"

# --------------------------------
# LOGIN ROUTE
# --------------------------------

@app.route("/login", methods=["POST"])
def login():

    data = request.json or {}
    username = data.get("username")
    password = data.get("password")

    if username in users and users[username] == password:
        access_token = create_access_token(identity=username)
        return jsonify(access_token=access_token)

    return jsonify({"error": "Invalid credentials"}), 401

# --------------------------------
# ANALYSIS ENDPOINT (PROTECTED)
# --------------------------------

@app.route("/analyze", methods=["POST"])
@jwt_required()
def analyze():

    current_user = get_jwt_identity()

    try:
        data = request.json or {}

        symptoms = data.get("symptoms", "")
        age = int(data.get("age", 0))

        health_result = analyze_health(symptoms, age)
        green_score = calculate_green_score(data)
        environmental_impact = estimate_environmental_impact(data)

        return jsonify({
            "user": current_user,
            "health_analysis": health_result,
            "green_score": green_score,
            "environmental_impact": environmental_impact,
            "disclaimer": app.config["MEDICAL_DISCLAIMER"]
        })

    except Exception as e:
        logging.error(f"Analyze Error: {str(e)}")
        return jsonify({"error": "Server processing error"}), 500

# --------------------------------
# REPORT GENERATION (PROTECTED)
# --------------------------------

@app.route("/generate-report", methods=["POST"])
@jwt_required()
def generate_report():

    current_user = get_jwt_identity()

    try:
        data = request.json or {}

        symptoms = data.get("symptoms", "")
        age = int(data.get("age", 0))

        health_result = analyze_health(symptoms, age)
        green_score = calculate_green_score(data)
        environmental_impact = estimate_environmental_impact(data)

        summary = generate_medical_summary(health_result)

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer)

        elements = []

        title_style = ParagraphStyle(
            name="title",
            fontSize=22,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#0ea5e9"),
            spaceAfter=20
        )

        normal_style = ParagraphStyle(
            name="normal",
            fontSize=11,
            leading=18
        )

        elements.append(
            Paragraph("🚑 CareBridge AI Integrated Report", title_style)
        )
        elements.append(Spacer(1, 20))

        table_data = [
            ["Field", "Value"],
            ["Generated By", current_user],
            ["Age", str(age)],
            ["Symptoms", symptoms],
            ["Risk Level", health_result["risk"]],
            ["Confidence", str(health_result["confidence"]) + "%"],
            ["Green Score", str(green_score)],
            ["Environmental Impact", str(environmental_impact)]
        ]

        table = Table(table_data, colWidths=[180, 320])

        table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0ea5e9")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.HexColor("#38bdf8")),
            ("PADDING", (0,0), (-1,-1), 10),
        ]))

        elements.append(table)
        elements.append(Spacer(1, 25))

        elements.append(Paragraph("🧠 Medical Insight", title_style))
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(summary, normal_style))
        elements.append(Spacer(1, 20))

        elements.append(Paragraph("⚠ Disclaimer", title_style))
        elements.append(Spacer(1, 10))
        elements.append(
            Paragraph(app.config["MEDICAL_DISCLAIMER"], normal_style)
        )

        doc.build(elements)
        buffer.seek(0)

        return send_file(
            buffer,
            mimetype="application/pdf",
            as_attachment=True,
            download_name="CareBridge_Report.pdf"
        )

    except Exception as e:
        logging.error(f"Report Error: {str(e)}")
        return jsonify({"error": "Report generation failed"}), 500

# --------------------------------
# Run Server
# --------------------------------

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)